# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5fae42de7b40fb1c06db9c703d4114aa69200dd2a227818db83d368470abcc82d202384d3e5d18e787ad29c7c1f28c424c1c0258006dd3c3eb2986163898fd

test:
  secret_key_base: efbe68e956dc79b81d3efaccb6db56486e654ab3af8be53e99021a783e0ac361dc89bad81ce4b7df545d25986084d908a2379379f8fcc5125ef9ff6701bcbd89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
